# Generated by Django 3.0.5 on 2022-04-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adult',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='children',
            name='children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='adults',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Adult'),
        ),
        migrations.AlterField(
            model_name='people',
            name='children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Children'),
        ),
    ]
