# Generated by Django 3.0.5 on 2022-04-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220405_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='adults',
        ),
    ]
